// User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// cart
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
